name: .NET 8 CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SLN_PATH: ./SM-Post/SM-Post.sln

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Check solution file
        run: cat ${{ env.SLN_PATH }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SLN_PATH }}

      - name: Build
        run: dotnet build ${{ env.SLN_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SLN_PATH }} --no-restore --verbosity normal
